household_power_consumption <- read.csv("~/R- Course/exdata_data_household_power_consumption/household_power_consumption.txt", sep=";")
View(household_power_consumption)
library(dplyr)
data<-tbl_df(household_power_consumption)
Dataset<-filter(data,Date=="1/2/2007" | Date=="2/2/2007")
Dataset$Date <- as.Date(Dataset$Date, format="%d/%m/%Y")
Dataset$Time <- strptime(Dataset$Time, format="%H:%M:%S")
Dataset$Time[1:1440]<- format(Dataset$Time[1:1440],"2007-02-01 %H:%M:%S")
Dataset$Time[1441:2880] <- format(Dataset$Time[1441:2880],"2007-02-02 %H:%M:%S")
par(mfrow=c(2,2))
 with(Dataset,plot(Time,Global_active_power,type = "l",xlab = "",ylab = "Global Active Power(kilowatts)"))
 with(Dataset,plot(Time,Voltage,col="black",type="l"))
 with(Dataset,plot(Time,Sub_metering_1,col="black",type="l",ylab = "Energy sub metering",xlab = ""))
 lines(Dataset$Time,Dataset$Sub_metering_2,col="red")
 lines(Dataset$Time,Dataset$Sub_metering_3,col="blue")
 legend("topright", col=c("black", "red", "blue"), lty=1, lwd=2, bty="n",
        legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"),cex=0.6)
 with(Dataset,plot(Time,Global_reactive_power,col="black",type="l"))
 dev.copy(png, file="plot4.png", height=480, width=480)
 dev.off()
